### PR TITLE
Update Clerk

### LINKED ISSUE #38: bug: Incorrect auth flow
### Provide environment information

None

### Describe the bug

The current flow sends two login emails at the same time, and unregistered users cannot create users in Clerk.

After some experimentation, the clerk's authentication workflow seems to look like this.

SignIn flow:
```tsx
await signIn.create({
  strategy: 'email_link',
  identifier: state.email,
  redirectUrl: `${window.location.origin}/`,
})

// user has account in clerk, email sent
// else throw: status===422 => this email is not signed up in clerk
```

SignUp flow:
```tsx
await signUp.create({
    emailAddress: state.email,
    password: nanoid(), // If the password is not provided, there seems to be some problems with the follow-up process? 
  })

await signUp.startMagicLinkFlow({
    redirectUrl: `${window.location.origin}/`,
  })

// email sent, click the link will verify and create the user, redirect to home
// or throw status===422: account exists
```

### Link to reproduction

https://acme-corp.jumr.dev/signin

### To reproduce

The current flow sends two login emails at the same time, and unregistered users cannot create users in Clerk.

截屏2023-04-27 18 23 50

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by perkinsjr**
This updates Clerk to latest and should fix #38

### CODE REVIEW

**Comment by perkinsjr** [comment]
@juliusmarminge this should fix that issue. I will also fix the middleware to the new middleware in the near future, much cleaner and easier to work with :)

**Comment by juliusmarminge** [comment]
> @juliusmarminge this should fix that issue. I will also fix the middleware to the new middleware in the near future, much cleaner and easier to work with :) 

Lovely! Cant wait to get back to this repo and build up the dashboard w/ payments and all other goodies! Just so much other shit to do rn 😰 thanks for staying on top of things!

**Comment by perkinsjr** [comment]
Thanks for being awesome and tell Theo to stop making you work so much.

**Comment by juliusmarminge** [comment]
> Thanks for being awesome and tell Theo to stop making you work so much.

Mostly school - building with Theo and T3 is my safe haven 😇😇

**Pull request merged**
